name: workflow

on:
  push:
    branches:
      - dev
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install
          npm i dotenv
          npm i mongoose
          npm i mocha
          npm i chai
          npm i chai-http
          npm i mochawesome
          npm i sinon
      - name: Run test
        run: npm test
